version: '3.8'
services:
  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
